export const IMF_REGION_NAME_TO_CODE = {
    'Egypt': 'EGY',
    'Ethiopia': 'ETH',
    'Ghana': 'GHA',
    'Kenya': 'KEN',
    'Libya': 'LBY',
    'Mauritius': 'MUS',
    'Morocco': 'MAR',
    'Nigeria': 'NGA',
    'Somalia': 'SOM',
    'South Africa': 'ZAF',
    'Sudan': 'SDN',
    'Tanzania': 'TZA',
    'Uganda': 'UGA',
    'Zimbabwe': 'ZWE',
    'Argentina': 'ARG',
    'Brazil': 'BRA',
    'Canada': 'CAN',
    'Chile': 'CHL',
    'Colombia': 'COL',
    'Ecuador': 'ECU',
    'Guyana': 'GUY',
    'Jamaica': 'JAM',
    'Mexico': 'MEX',
    'Peru': 'PER',
    'United States of America': 'USA',
    'Uruguay': 'URY',
    'Venezuela': 'VEN',
    'Afghanistan': 'AFG',
    'Bahrain': 'BHR',
    'Bangladesh': 'BGD',
    'Bhutan': 'BTN',
    'China': 'CHN',
    'Hong Kong': 'HKG',
    'India': 'IND',
    'Indonesia': 'IDN',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Israel': 'ISR',
    'Japan': 'JPN',
    'Jordan': 'JOR',
    'Kazakhstan': 'KAZ',
    'Kuwait': 'KWT',
    'Lebanon': 'LBN',
    'Malaysia': 'MYS',
    'Myanmar': 'MMR',
    'Nepal': 'NPL',
    'Oman': 'OMN',
    'Pakistan': 'PAK',
    'Philippines': 'PHL',
    'Qatar': 'QAT',
    'Saudi Arabia': 'SAU',
    'Singapore': 'SGP',
    'South Korea': 'KOR',
    'Sri Lanka': 'LKA',
    'Taiwan': 'TWN',
    'Tajikistan': 'TJK',
    'Thailand': 'THA',
    'Turkey': 'TUR',
    'Turkmenistan': 'TKM',
    'United Arab Emirates': 'ARE',
    'Uzbekistan': 'UZB',
    'Vietnam': 'VNM',
    'Yemen': 'YEM',
    'Austria': 'AUT',
    'Belgium': 'BEL',
    'Czech Republic': 'CZE',
    'Denmark': 'DNK',
    'Finland': 'FIN',
    'France': 'FRA',
    'Georgia': 'GEO',
    'Germany': 'DEU',
    'Greece': 'GRC',
    'Hungary': 'HUN',
    'Ireland': 'IRL',
    'Italy': 'ITA',
    'Luxembourg': 'LUX',
    'Netherlands': 'NLD',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'PRT',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'Serbia': 'SRB',
    'Slovak Republic': 'SVK',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'CHE',
    'Ukraine': 'UKR',
    'United Kingdom': 'GBR',
    'Australia': 'AUS',
    'New Zealand': 'NZL',
    'ASEAN-5': 'AEN',
    'Advanced economies': 'ADE',
    'Emerging Asia': 'EMA',
    'Emerging Market Economies': 'EME',
    'Euro area': 'EUR',
    'European Union': 'EUU',
    'G7 Countries': 'G7C',
    'Latin America, Caribbean': 'LAM',
    'Middle East,  Central Asia': 'MEA',
    'Otr Adv Economies (ex G7, Euro area)': 'OAE',
    'World': 'WLD',
};